#include "p16f877a.inc"
__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF
LIST P=16F877A
ORG 0X00
CBLOCK 0X20
D1 
D2
D3
UNIDADES
DECENAS
ENDC

BSF STATUS, RP0 ; banco 1
CLRF TRISB
CLRF TRISC
BSF TRISD, 0
    
BCF STATUS, RP0 ; banco 0
CLRF UNIDADES
CLRF DECENAS
    
;PROGRAMA
PROGRAMA
    ALTO
    BTFSS PORTD,0 ; SI EL PIN ESTA EN ALTO SE SALTA UNA LINEA
    GOTO BAJO
    CALL INCREMENTAR ; SUBRUTINA CONTADOR ASCENDENTE
    CALL DELAY_500MS ; DELAY DE 0,5 SEGS
    BAJO
    BTFSC PORTD,0 ; SI EL PIN ESTA EN BAJO SE SALTA UNA LINEA
    GOTO ALTO
    CALL DECREMENTAR ; SUBRUTINA CONTADOR DESCENDENTE
    CALL DELAY_500MS ; DELAY DE 0,5 SEG
    GOTO PROGRAMA

;MOSTRAR NUMEROS
MOSTRAR_DISPLAY
    MOVF UNIDADES,W ; MUEVO EL VALOR DE UNIDADES A W
    CALL TABLA ; LLAMO A LA SUBRUTINA TABLA
    MOVWF PORTC ; MOVEMOS EL RESULTADO AL PUERTO C
   
    MOVF DECENAS,W ; MUEVO EL VALOR DE DECENAS A W
    CALL TABLA ; LLAMO A LA SUBRUTINA TABLA
    MOVWF PORTB ;; MOVEMOS EL RESULTADO AL PUERTO C
    RETURN

; CONTADOR ASCENDENTE
INCREMENTAR
    CALL MOSTRAR_DISPLAY ; SUBRUTINA PARA MOSTRAR NUMEROS
    INCF UNIDADES,F ; INCREMENTO UNIDADES EN 1
    MOVF UNIDADES,W ; MUEVO VARIABLE A W
    SUBLW .10 ; LE RESTO 10
    BTFSS STATUS,Z ; PREGUNTO SI ES 0
    RETURN ; CONTINUO CONTEO
    CLRF UNIDADES ; REINICIO VARIABLE
    INCF DECENAS,F ; INCREMENTO DECENAS EN 1
    MOVF DECENAS,W ; MUEVO VARIABLE A W
    SUBLW .10 ; LE RESTO 10
    BTFSS STATUS,Z ; PREGUNTO SI ES 0
    RETURN ; CONTINUO CONTEO
    CLRF DECENAS
    RETURN

;CONTADOR DESCENDENTE
DECREMENTAR
    CALL MOSTRAR_DISPLAY ; SUBRUTINA PARA MOSTRAR NUMEROS
    DECF UNIDADES,F ; DECREMENTO UNIDADES EN 1
    MOVF UNIDADES,W ; MUEVO VARIABLE A W
    SUBLW .255
    BTFSS STATUS,Z 
    RETURN ; CONTINUO CONTEO
    MOVLW .9
    MOVWF UNIDADES
    DECF DECENAS,F
    MOVF DECENAS,W
    SUBLW .255
    BTFSS STATUS,Z
    RETURN
    MOVLW .9
    MOVWF DECENAS
    RETURN

; TABLA PARA NUMEROS 
TABLA
    ADDWF PCL,1
    RETLW b'00111111' ;0
    RETLW b'00000110' ;1
    RETLW b'01011011' ;2
    RETLW b'01001111' ;3
    RETLW b'01100110' ;4
    RETLW b'01101101' ;5
    RETLW b'01111101' ;6
    RETLW b'00100111' ;7
    RETLW b'01111111' ;8
    RETLW b'01101111' ;9
    
;DELAY DE 0,5 SEG
DELAY_500MS
    MOVLW d'13'
    MOVWF D1
    ARRIBA
    MOVLW d'255'
    MOVWF D2
    BUCLE1
    MOVLW d'255'
    MOVWF D3
    REPITE1
    DECFSZ D3,1
    GOTO REPITE1
    DECFSZ D2,1
    GOTO BUCLE1
    DECFSZ D1,1
    GOTO ARRIBA
    RETURN

END


